#开发环境配置
spring:
  profiles: test
  #自定义配置属性
  #视图配置
  mvc:
    static-path-pattern: /static/**
  # 开启aop支持
  aop:
    proxy-target-class: true
  datasource:
      url: jdbc:mysql://localhost:3306/lzhpo-shiro?useSSL=false&serverTimezone=CTT&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      # hikari连接池配置
      hikari:
        # 最小空闲连接数量
        minimum-idle: 5
        # 空闲连接存活最大时间，默认600000（10分钟）
        idle-timeout: 180000
        # 连接池最大连接数，默认是10
        maximum-pool-size: 10
        # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        auto-commit: true
        # 连接池母子
        pool-name: MyHikariCP
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        max-lifetime: 1800000
        # 数据库连接超时时间,默认30秒，即30000
        connection-timeout: 30000
        connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 2
    timeout: 30000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
